SIM = questa

SIM_ARGS+=-L fifo_generator_v13_2_5

TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../../IP/fifo_generator_0/sim/*.v

MODULE = test
TOPLEVEL = fifo_generator_0

include $(shell cocotb-config --makefiles)/Makefile.sim